// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnmtqoxrygesqiapdmkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubXRxb3hyeWdlc3FpYXBkbWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTc2MzMsImV4cCI6MjA1Njc5MzYzM30.V41K-7IrkfbFXKOYdFjtxa0zowDQvrD1wZoi1I9FlR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);